### ISSUE TITLE
Transform.py中transform函数中第5种augment方法jaccard

### ISSUE THREAD

**Issue by roachsinai** [daniaokuye/SSD_data_augment#2]
第5种augment方法是调用jaccard.py中的random_crop实现的。您的实现可以理解为：

在原始图片随机选择一个矩形区域，如果这个区域和某一个object的IOU满足条件，且bounding box的中心在这个矩形区域中的话就将这个矩形区域对应的部分截取出来作为新增的图片，而刚才提到的IOU区域成为新的bounding box并更新对应的'bndbox'值。

是这样么？

**Comment by lidc54** [comment]
可以这样理解，还有原文中是有梯度的选择了IOU值。
实际上，对于某些图片来说随机裁剪图片（或batch）是解释不通的，比如一个抱猫的人近景图片（在ssd中是示例图片），需要裁剪出包括人脸的区域才能保证label的正确性。所以另外一种方式是确定一个较大的框作为基础框来裁剪，相应的低IOU（比如0.3）的样本，可以选择更大的裁剪区域，然后缩放为更小的图片（如果有多物体的话，还可以使用填充某些背景图片--自己生成的或者背景图片库或者在原图中采集的）————这种方式更合理一些，即保证了样本增多，保证样本尺度上的多样，同时保证区域语义信息的准确。

**Comment by roachsinai** [comment]
谢谢回复，对您说的更合理的方法没有理解。可以的话希望再指点一下！:-))) 谢谢！

+ `较大的框作为基础框`是说随机选择出一个较大的矩形（剪裁）区域么？
+ 缩放为更小的图片不理解因为如果模型是vgg_300那不应该都缩小为300x300么？
+ 填充背景图片这个是将随机剪裁的图片嵌入到一个图片中再缩放到300x300（如果选择vgg_300）么？

**Comment by lidc54** [comment]
1. 选择较大的基础框，可以避免裁剪出和目标无关的框。2.我所说的缩放是相对于目标框而言的，即最终呈现在300*300的图片中的目标框是缩小的就好。3.正是这个意思，避免背景中包含有效目标就行，比如pascal voc 20类别之外的类别
跳出来一点看，数据增广的目的就是产生多样性的样本，其中之一包括多尺度。

发送自 Windows 10 版邮件应用

发件人: SinaiHao
发送时间: 2018年5月30日 10:09
收件人: daniaokuye/SSD_data_augment
抄送: daniaokuye; State change
主题: Re: [daniaokuye/SSD_data_augment] Transform.py中transform函数中第5种augment方法jaccard (#2)

谢谢回复，对您说的更合理的方法没有理解。可以的话希望再指点一下！:-))) 谢谢！
• 较大的框作为基础框是说随机选择出一个较大的矩形（剪裁）区域么？
• 缩放为更小的图片不理解因为如果模型是vgg_300那不应该都缩小为300x300么？
• 填充背景图片这个是将随机剪裁的图片嵌入到一个图片中再缩放到300x300（如果选择vgg_300）么？

**Comment by roachsinai** [comment]
关于回复的第二点，可以理解为：

第5种augment方法调用jaccard.py中的random_crop实现时，可以设置剪裁的都是`较大的框作为基础框`并设定不同的IOU，是这样么？

---

谢谢:-(((

**Comment by lidc54** [comment]
可以

发送自 Windows 10 版邮件应用

发件人: SinaiHao
发送时间: 2018年5月30日 11:26
收件人: daniaokuye/SSD_data_augment
抄送: daniaokuye; State change
主题: Re: [daniaokuye/SSD_data_augment] Transform.py中transform函数中第5种augment方法jaccard (#2)

关于回复的第二点，可以理解为：
第5种augment方法调用jaccard.py中的random_crop实现时，可以设置剪裁的都是较大的框作为基础框并设定不同的IOU，是这样么？

谢谢:-(((
